_meta_deps: !include "../meta/deps.yaml"
_meta_defs: !include "../meta/defaults.yaml"

<<: *defaults

name: cqrs-example
version: "0.11.0"
synopsis: Example for cqrs package
description: Example for cqrs package
category: Web

extra-source-files:
  - static/bower_components/bootstrap/dist/css/bootstrap.min.css
  - static/bower_components/superagent/superagent.js
  - static/index.html
  - static/css/style.css
  - static/js/bundle.js

executables:
  cqrs-example:
    main: CQRSExample/Main.hs
    dependencies:
      - *dep_aeson
      - *dep_async
      - *dep_base
      - *dep_base16-bytestring
      - *dep_blaze-builder
      - *dep_bytestring
      - *dep_cereal
      - *dep_containers
      - *dep_cqrs-core
      - *dep_cqrs-memory
      - *dep_cqrs-postgresql
      - *dep_deepseq
      - *dep_pg-harness-client
      - *dep_postgresql-simple
      - *dep_random
      - *dep_resource-pool
      - *dep_scotty
      - *dep_stm
      - *dep_text
      - *dep_transformers
      - *dep_unliftio-core
      - *dep_unliftio-streams
      - *dep_warp
      - *dep_wai-middleware-static
      - *dep_wai-extra
    other-modules:
      - CQRSExample.Aggregates
      - CQRSExample.AggregateAction
      - CQRSExample.Commands
      - CQRSExample.Events
      - CQRSExample.Json
      - CQRSExample.Notifications
      - CQRSExample.Query
      - CQRSExample.Routing
      - CQRSExample.TaskId
    source-dirs: src
